baseURL = "https://ximuli.github.io/"
languageCode = "zh-CN"
title = "乐亦栗的个人网站"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[Languages]
[languages.zh]
  languageCode = "zh-CN"
  languageName = "简体中文"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  
  [[menu.main]]
    name = "联系我"
    url = "/contact/"
    weight = 4
  
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

[params]
    since = 2016
    author = "leyili"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "用心用心再用心"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "乐亦栗的个人网站" # site description
    keywords = "前端，个人网站，前端笔记，随笔，杂文" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    # GitHub = "https://github.com/ximuli"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Email   = "leyili.dev@gmail.com"

